version: 1
version_name: 1 - Init project

schemas:
  tables: gic/databases/sqitch.git/scripts/gen/schema/tables
  functions: gic/databases/sqitch.git/scripts/gen/schema/functions
  restricted: gic/databases/sqitch.git/scripts/gen/schema/.restricted/tables