
version: 1
version_name: 1 - Init
fields:
  - name: id
    old_name:
    type: bigint
    primary: true
    not_null: true
  - name: product_id
    old_name:
    type: bigint
  - name: attribute_id
    old_name:
    type: bigint
  - name: value
    old_name:
    type: text
  - name: created_at
    old_name:
    type: timestamp
  - name: updated_at
    old_name:
    type: timestamp
indexs:
  - name: product_attribute_attribute_id_idx
    key: attribute_id
    using: btree
  - name: product_attribute_created_at_idx
    key: created_at
    using: btree
  - name: product_attribute_id_idx
    key: id
    using: btree
  - name: product_attribute_product_id_idx
    key: product_id
    using: btree
  - name: product_attribute_updated_at_idx
    key: updated_at
    using: btree
  - name: product_attribute_value_idx
    key: value
    using: btree

drop_fields:
#  -name: fieldname
#  -name: fieldname
