
version: 1
version_name: 1 - Init
fields:
  - name: id
    old_name:
    type: bigint
    primary: true
    not_null: true
  - name: merchant_order_id
    old_name:
    type: bigint
  - name: sku
    old_name:
    type: text
  - name: name
    old_name:
    type: text
  - name: category
    old_name:
    type: text
  - name: link
    old_name:
    type: text
    not_null: true
  - name: price_x
    old_name:
    type: integer
  - name: currency
    old_name:
    type: text
  - name: gift
    old_name:
    type: boolean
  - name: number_of_set
    old_name:
    type: integer
  - name: item_in_set
    old_name:
    type: integer
  - name: package_info_id
    old_name:
    type: bigint
  - name: unit_weight
    old_name:
    type: integer
  - name: created_at
    old_name:
    type: timestamptz
  - name: updated_at
    old_name:
    type: timestamptz
  - name: action_admin_id
    old_name:
    type: bigint
  - name: description
    old_name:
    type: text
  - name: name_en
    old_name:
    type: text
  - name: name_kr
    old_name:
    type: text
  - name: name_cn
    old_name:
    type: text
  - name: brand
    old_name:
    type: text
  - name: image
    old_name:
    type: text
indexs:
  - name: product_category_idx
    key: category
    using: btree
  - name: product_created_at_idx
    key: created_at
    using: btree
  - name: product_gift_idx
    key: gift
    using: btree
  - name: product_id_idx
    key: id
    using: btree
  - name: product_merchant_order_id_idx
    key: merchant_order_id
    using: btree
  - name: product_package_info_id_idx
    key: package_info_id
    using: btree
  - name: product_sku_idx
    key: sku
    using: btree
  - name: product_updated_at_idx
    key: updated_at
    using: btree

drop_fields:
#  -name: fieldname
#  -name: fieldname
