
version: 1
version_name: 1 - Init
fields:
  - name: pricing_config_id
    type: bigint
    not_null: true
  - name: revision
    type: bigint
    not_null: true
  - name: user_id
    type: bigint
    not_null: true
  - name: updated_at
    type: timestamp
    not_null: true
  - name: changes
    type: jsonb
indexs:
  - name: pricing_config_history_revision_idx
    key: revision
    using: btree
