
version: 1
version_name: 1 - Init
fields:
  - name: id
    type: bigint
    primary: true
    not_null: true
  - name: pricing_config_id
    type: bigint
  - name: service_fee_id
    type: bigint
  - name: active
    type: boolean
  - name: created_at
    type: timestamp
  - name: updated_at
    type: timestamp
