
version: 1
version_name: 1 - Init
fields:
  - name: id
    type: bigint
    not_null: true
  - name: merchant_order_id
    type: bigint
  - name: sku
    type: text
  - name: name
    type: text
  - name: category
    type: text
  - name: link
    type: text
    not_null: true
  - name: price_x
    type: integer
  - name: currency
    type: text
  - name: gift
    type: boolean
  - name: number_of_set
    type: integer
  - name: item_in_set
    type: integer
  - name: package_info_id
    type: bigint
  - name: unit_weight
    type: integer
  - name: created_at
    type: timestamp
  - name: updated_at
    type: timestamp
  - name: action_admin_id
    type: bigint
  - name: description
    type: text
  - name: name_en
    type: text
  - name: name_kr
    type: text
  - name: name_cn
    type: text
  - name: brand
    type: text
  - name: image
    type: text
indexs:
  - name: product_category_idx
    key: category
    using: btree
  - name: product_created_at_idx
    key: created_at
    using: btree
  - name: product_gift_idx
    key: gift
    using: btree
  - name: product_id_idx
    key: id
    using: btree
  - name: product_merchant_order_id_idx
    key: merchant_order_id
    using: btree
  - name: product_package_info_id_idx
    key: package_info_id
    using: btree
  - name: product_sku_idx
    key: sku
    using: btree
  - name: product_updated_at_idx
    key: updated_at
    using: btree
