
version: 1
version_name: 1 - Init
fields:
  - name: id
    old_name:
    type: bigint
    not_null: true
  - name: name
    old_name:
    type: text
    not_null: true
  - name: code
    old_name:
    type: text
    not_null: true
  - name: description
    old_name:
    type: text
    not_null: true
  - name: service_type
    old_name:
    type: text
  - name: active
    old_name:
    type: boolean
  - name: updated_at
    old_name:
    type: date
  - name: action_admin_id
    old_name:
    type: text
indexs:
  - name: "PK_service"
    key: id
    using: btree
    unique: true

drop_fields:
#  -name: fieldname
#  -name: fieldname
