
version: 1
version_name: 1 - Init
fields:
  - name: id
    type: bigint
    not_null: true
  - name: name
    type: text
    not_null: true
  - name: code
    type: text
    not_null: true
  - name: description
    type: text
    not_null: true
  - name: service_type
    type: text
  - name: active
    type: boolean
  - name: updated_at
    type: date
  - name: action_admin_id
    type: text
indexs:
  - name: "PK_service"
    key: id
    using: btree
    unique: true
